services:
  - type: web
    name: trend-matrix-pro
    runtime: python
    buildCommand: |
  mkdir -p /opt/render/nltk_data
  pip install --upgrade pip
  pip install numpy==1.24.3
  pip install huggingface-hub==0.4.0  # Explicit install
  pip install -r requirements.txt
  python -c "import nltk; nltk.download('vader_lexicon', download_dir='/opt/render/nltk_data')"
    startCommand: gunicorn app:server
    plan: free
    envVars:
      - key: NLTK_DATA
        value: /opt/render/nltk_data
      
      # Get free key: https://newsapi.org/register
      - key: NEWSAPI_KEY
        value: your_newsapi_key  # Replace after registration
      
      # Get free key: https://www.alphavantage.co/support/#api-key
      - key: ALPHAVANTAGE_KEY
        value: your_alphavantage_key  # Replace after registration
