version: 1
services:
  - type: web
    name: trend-matrix-pro
    runtime: python
    buildCommand: |
      mkdir -p "${NLTK_DATA}"
      mkdir -p /opt/render/.cache/huggingface/hub
      pip install --upgrade pip
      pip install --no-cache-dir --use-pep517 --prefer-binary -r requirements.txt
      python -c "import nltk; nltk.download('vader_lexicon', download_dir='${NLTK_DATA}')"
    startCommand: |
      gunicorn --workers 1 --threads 2 --timeout 180 app:server
    plan: free
    envVars:
      - key: NLTK_DATA
        value: /opt/render/cache/nltk_data
      - key: TRANSFORMERS_CACHE
        value: /opt/render/cache/huggingface
      - key: OMP_NUM_THREADS
        value: 1
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: NEWSAPI_KEY
        value: your_newsapi_key
      - key: ALPHAVANTAGE_KEY
        value: your_alphavantage_key
