services:
  - type: web
    name: trend-matrix-pro
    runtime: python
    pythonVersion: "3.10.10"
    buildCommand: |
      mkdir -p "${NLTK_DATA}"
      pip install --upgrade pip
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('vader_lexicon', download_dir='${NLTK_DATA}')"
    startCommand: gunicorn --workers 2 --timeout 120 app:server
    plan: free
    envVars:
      - key: NLTK_DATA
        value: /opt/render/nltk_data
      - key: NEWSAPI_KEY
        value: your_newsapi_key
      - key: ALPHAVANTAGE_KEY
        value: your_alphavantage_key
      - key: OMP_NUM_THREADS
        value: 2
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: PYTHONPYCACHEPREFIX
        value: /tmp/pycache
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
