services:
  - type: web
    name: trend-matrix-pro
    runtime: python
    pythonVersion: "3.10.10"
    buildCommand: |
      mkdir -p "${NLTK_DATA}"
      export CARGO_HOME=/opt/render/.cargo
      pip install --upgrade pip
      pip install --use-pep517 --no-build-isolation -r requirements.txt
      python -m nltk.downloader -d "${NLTK_DATA}" vader_lexicon
    startCommand: gunicorn --workers 2 --timeout 120 app:server
    envVars:
      - key: CARGO_HOME
        value: /opt/render/.cargo
      - key: RUSTUP_HOME
        value: /opt/render/.rustup
      # ... (previous env vars remain)
